# 1. Create the Student Database

In [83]:
students <- data.frame(
    StudentID = c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
    Programming_Grade =c(88, 72, 91, 78, 65, 85, 74, 82),
    Math_Grade = c(85, 70, 88, 80, 68, 90, 73, 79),
    Attendance = c(92, 80, 95, 88, 70, 91, 76, 85),
    Prerequisite = c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)
write.csv(students, "Students.csv")

students

  StudentID Programming_Grade Math_Grade Attendance Prerequisite
1 S001      88                85         92         Yes
2 S002      72                70         80         No
3 S003      91                88         95         Yes
4 S004      78                80         88         Yes
5 S005      65                68         70         No
6 S006      85                90         91         Yes
7 S007      74                73         76         No
8 S008      82                79         85         Yes

2. Explore the Data

In [84]:
data <- read.csv("Students.csv")

head(data)
cat("\n")
summary(data)

  X StudentID Programming_Grade Math_Grade Attendance Prerequisite
1 1 S001      88                85         92         Yes
2 2 S002      72                70         80         No
3 3 S003      91                88         95         Yes
4 4 S004      78                80         88         Yes
5 5 S005      65                68         70         No
6 6 S006      85                90         91         Yes

       X            StudentID Programming_Grade   Math_Grade      Attendance
 Min.   :1.00   Length   :8   Min.   :65.00     Min.   :68.00   Min.   :70.00
 1st Qu.:2.75   N.unique :8   1st Qu.:73.50     1st Qu.:72.25   1st Qu.:79.00
 Median :4.50   N.blank  :0   Median :80.00     Median :79.50   Median :86.50
 Mean   :4.50   Min.nchar:4   Mean   :79.38     Mean   :79.12   Mean   :84.62
 3rd Qu.:6.25   Max.nchar:4   3rd Qu.:85.75     3rd Qu.:85.75   3rd Qu.:91.25
 Max.   :8.00                 Max.   :91.00     Max.   :90.00   Max.   :95.00
    Prerequisite
 Length   :8
 N.unique :2
 N.blank  :0
 Min.nchar:2
 Max.nchar:3

In [85]:
cat("Columns:",ncol(students))
cat("\nRows:", nrow(students))
cat("\nMax:", max(students$Programming_Grade))
cat("\nMax:", max(students$Math_Grade))

Columns: 5
Rows: 8
Max: 91
Max: 90

3. Enter a Student ID

In [89]:
student_ID = readline("Enter Student ID: ")
print(student_ID)

Enter Student ID: S001
[1] "S001"

4. Search the Data Frame

In [90]:
student <- students[
  students$StudentID == student_ID,
]
student

  StudentID Programming_Grade Math_Grade Attendance Prerequisite
1 S001      88                85         92         Yes

5. Check if the students exist

In [92]:

if (nrow(student) > 0) {
  print(student)
} else {
  print("Not Found")
}

  StudentID Programming_Grade Math_Grade Attendance Prerequisite
1      S001                88         85         92          Yes

6. Extract Student Information

In [106]:
programming <- student$Programming_Grade

cat("Programming Grade: ", programming)

math <- student$Math_Grade
cat("\nMath Grade: ", math)

att <- student$Attendance
cat("\nAttendance: ", att)

prq <- student$Prerequisite
cat("\nPrerequesite: ", prq)

Programming Grade:  88
Math Grade:  85
Attendance:  92
Prerequesite:  Yes

7. Implement the Rules

In [122]:
eligibility <- function(programming, math, att, prq) {
  if (programming >= 80 && math >= 75 && att >= 80 && prq == "Yes"){
    return("Eligible")
  } else if (programming >= 75 && math >= 70 && att >= 75){
    return("Conditional")
  } else {
    return("Not Eligible")
  }
}

8. Apply all the Function

In [123]:
students$Status <- mapply(
  eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  StudentID Programming_Grade Math_Grade Attendance Prerequisite Status
1 S001      88                85         92         Yes          Eligible
2 S002      72                70         80         No           Not Eligible
3 S003      91                88         95         Yes          Eligible
4 S004      78                80         88         Yes          Conditional
5 S005      65                68         70         No           Not Eligible
6 S006      85                90         91         Yes          Eligible
7 S007      74                73         76         No           Not Eligible
8 S008      82                79         85         Yes          Eligible

9. Recommendation

In [125]:
student_Recommendation <- function(eligibility){
  if(eligibility == "Eligible"){
    return("Student may enroll")
  }else if (eligibility == "Conditional") {
    return("Consult academic yutor")
  }else {
    return("Complete requirements before enrollment.")
  }
}
student_Recommendation("Eligible")

[1] "Student may enroll"

10. Complete the table

In [126]:
students$Recomendation <- mapply(
  student_Recommendation,
  students$Status
)

students

  StudentID Programming_Grade Math_Grade Attendance Prerequisite Status
1 S001      88                85         92         Yes          Eligible
2 S002      72                70         80         No           Not Eligible
3 S003      91                88         95         Yes          Eligible
4 S004      78                80         88         Yes          Conditional
5 S005      65                68         70         No           Not Eligible
6 S006      85                90         91         Yes          Eligible
7 S007      74                73         76         No           Not Eligible
8 S008      82                79         85         Yes          Eligible
  Recomendation
1 Student may enroll
2 Complete requirements before enrollment.
3 Student may enroll
4 Consult academic yutor
5 Complete requirements before enrollment.
6 Student may enroll
7 Complete requirements before enrollment.
8 Student may enroll

In [131]:
student_ID <- readline(prompt = "Enter Student ID: ")

student <- students[students$StudentID == student_ID,]

if (nrow(student) > 0) {
  cat("\n=========================================\n")
  cat("         COURSE ENROLLMENT ADVISER \n")
  cat("\n=========================================\n")
  cat("Student ID:", student$StudentID, "\n\n")
  cat(sprintf("Programming Grade: %.2f%%\n", student$Programming_Grade))
  cat(sprintf("Math Grade: %.2f%%\n", student$Math_Grade))
  cat(sprintf("Attendance: %.2f%%\n", student$Attendance))
  cat("Prerequisite:", student$Prerequisite, "\n\n")
  cat("Enrollment Status:\n")
  cat(student$Status, "\n\n")
  cat("Recommendation:\n")
  cat(student$Recomendation, "\n")
  cat("========================================\n")
} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S001

=========================================
         COURSE ENROLLMENT ADVISER

=========================================
Student ID: S001

Programming Grade: 88.00%
Math Grade: 85.00%
Attendance: 92.00%
Prerequisite: Yes

Enrollment Status:
Eligible

Recommendation:
Student may enroll
========================================