My First R Program

1. Print

In [ ]:
print ("Hello World!")

[1] "Hello World!"

2. Variables and Data Types

In [ ]:
myString <- ("Hello, World!")
num <- 10
floatingNum <- 8.5
isBool <- TRUE

class(myString)
class(num)
class(floatingNum)
class(isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

3. Numerical Operators

In [ ]:
x = 5
y = 3

add = x + y
sub = x - y
mul = x * y
div = x / y
mod = x % y

print(f"+ {add}")
print(f"- {sub}")
print(f"* {mul}")
print(f"/ {div}")
print(f"% {mod}")

ERROR: Error in parse(text = input): <text>:8:9: unexpected input
7: div = x / y
8: mod = x % y
           ^

In [ ]:
name = readline("Enter Name:")
print (paste("Name:", name))

Enter Name:Mike Dawgie
[1] "Name: Mike Dawgie"

Decision Making

In [ ]:
grade <- 80

if(grade < 75)(
   print ("Failed")
)else (
   print ("Passed")
)

[1] "Passed"

[1] "Passed"

Loop

In [ ]:
for(i in 1:5)(
    print(i)
)

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

Function

In [ ]:
addNumber <- function(a,b)(
    return(a+b)
)

addNumber(5, 3)

[1] 8

Vectors

In [ ]:
grades <- c(90,88,96,83,91)

grades

cat("MEAN:", mean(grades))
cat("\nMAX:", max(grades))
cat("\nMIN:", min(grades))
cat("\nSUM:", sum(grades))
cat("\nLENGTH:", length(grades))

[1] 90 88 96 83 91

MEAN: 89.6
MAX: 96
MIN: 83
SUM: 448
LENGTH: 5

Matrices

In [ ]:
A <- matrix(c(1,2,3,4,5,6), nrow = 2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

Lists

In [ ]:
student <- list(
    Name= "John",
    Age = 20,
    GPA = 1.5
)

student

$Name
[1] "John"

$Age
[1] 20

$GPA
[1] 1.5

Data Frames

In [ ]:
students <- data.frame(
    Name = c("John", "Mary", "Anna"),
    Age = c(20,21,19),
    GPA = c(1.5,1.8,1.4)
)

students

write.csv(students, "students.csv")

  Name Age GPA
1 John 20  1.5
2 Mary 21  1.8
3 Anna 19  1.4

Reading CSV Files

In [ ]:
data <- read.csv("students.csv")

head(data)

  X Name Age GPA
1 1 John 20  1.5
2 2 Mary 21  1.8
3 3 Anna 19  1.4